## Section II Python and Vectorization

#### 1. Vectorization


##### (1) Example of calculating *z* in logistic regression
$z = w^Tx + b, \mathrm{where:} w = \left[\begin{array}{c}
w_1\\
w_2\\
\vdots\\
w_{n_x}
\end{array}\right], x = \left[\begin{array}{c}
x_1\\
x_2\\
\vdots\\
x_{n_x}
\end{array}\right]; w \in \textbf{R}^{n_{x}}, x \in \textbf{R}^{n_{x}}$

- **For non-vectorized (i.e. *for* loop) case**:
    - 1. $z = 0$
    - 2. for *i* in range($n_x$):
        - 3-1. $z\ +=\ w^{(i)}x^{(i)}$
    - 4. $z\ +=\ b$
- **for vectorized case**:
    - 1. $z = \mathrm{np.dot}(w,x)+b$

##### (2) Vectorization saving time (Python)

In [7]:
import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [8]:
# Get the computation time with vectorized method np.dot
tic = time.time()
c = np.dot(a,b)
toc = time.time()

print('c = ' + str(c) + ', Vectorized version:' +str(1000*(toc-tic)) + 'ms')

c = 249869.8724567009, Vectorized version:0.9975433349609375ms


In [9]:
# Get the computation time with non-vectorized method for loop 
tic = time.time()
c = 0
for ai, bi in zip(a,b):
    c += ai*bi
toc = time.time()
print('c = ' + str(c) + ', Non-vectorized version:' + str(1000*(toc-tic))+'ms')

c = 249869.87245669932, Non-vectorized version:328.11975479125977ms


- Comparing the two codes: vectorization speeds up more than **300** times!
- Using the internal functions (like *np.dot*) can enable python numpy to use parallelism methods to compute with GPU and CPU much faster.
- **Rule of thumb**: whenever possible, avoid explicit *for* loops.

##### (3) Other vectorization examples
$\boxed{\textbf{u}_{m} = \textbf{A}_{mn}\textbf{v}_{n}}$

- **For non-vectorized (i.e. *for* loop) case**:
    - 1. $\textbf{u} = \mathrm{np.zeros}((n,1))$
    - 2. *for* $i\ \mathrm{in}\ \mathrm{range}(m)$:
        - 3. *for* $j\ \mathrm{in}\ \mathrm{range}(n)$:
            - 4. $\textbf{u}_i\ += \textbf{A}_{ij}*\textbf{v}_j$
- **for vectorized case**:
    - 1. $\textbf{u} = \mathrm{np.dot}(\textbf{A},\textbf{v})$  
$\qquad\qquad\qquad\qquad\qquad\qquad\qquad$  

$\boxed{\textbf{v} =  \left[\begin{array}{c}
v_1\\
v_2\\
\vdots\\
v_n
\end{array}\right] \Longrightarrow \textbf{u} = \left[\begin{array}{c}
e^{v_1}\\
e^{v_2}\\
\vdots\\
e^{v_n}
\end{array}\right]}$
- **For non-vectorized (i.e. *for* loop) case**:
    - 1. $\textbf{u} = \mathrm{np.zeros}((n,1))$
    - 2. *for* $v_i\ \mathrm{in}\ \textbf{v}$:
        - 3. $u_i = e^{v_i}$
- **for vectorized case**:
    - 1. $\textbf{u} = \mathrm{np.exp}(\textbf{v})$

$\qquad\qquad\qquad\qquad\qquad\qquad\qquad$
- **Other vectorization codes**:
    - np.log(v) - computes natural logarithm of every elements in *v*
    - np.abs(v) - computes the absolute value of every elements in *v*
    - np.maximum(u,v) - compares every elements in *u* and *v* and provides the maximum of every pair
    - v**2 - computes the square of every elements in *v*
    - 1/v - computes the inverse of every elements in *v*

#### 2. Vectorizing Logistic Regression

-   **Original code** (from ***Week2-1**: 7. Logistic Regression Gradient Descent*)
>    - 1. Set: $J = 0, \mathrm{d}w_1 = 0, \mathrm{d}w_2 = 0, \mathrm{d}b = 0$
>    - 2. *for* $i = 1\ to\ m$:
>        - 3-1. $z^{(i)} = w^Tx^{(i)}+b$
>        - 3-2. $a^{(i)} = \sigma (z^{(i)})$
>        - 3-3. $J\ +=\ y^{(i)}\log a^{(i)} + (1-y^{(i)})\log(1-a^{(i)}) $
>        - 3-4. $\mathrm{d}z^{(i)} = a^{(i)} - y^{(i)}$
>        - 3-5. $\mathrm{d}w_1\ +=\ x_1^{(i)}\mathrm{d}z^{(i)}$
>        - 3-6. $\mathrm{d}w_2\ +=\ x_2^{(i)}\mathrm{d}z^{(i)}$ - If more than 2 features: another *for* loop
>        - 3-7. $\mathrm{d}b\ +=\ \mathrm{d}z^{(i)}$
>    - 4-1. $J := J/m$ - Key step: get *J* value to determine the performance
>    - 4-2. $\mathrm{d}w_1 := \mathrm{d}w_1/m$
>    - 4-3. $\mathrm{d}w_2 := \mathrm{d}w_2/m$
>    - 4-4. $\mathrm{d}b := \mathrm{d}b/m$
>    - 5-1. $w_1 := w_1 - \alpha\mathrm{d}w_1$
>    - 5-2. $w_2 := w_2 - \alpha\mathrm{d}w_2$
>    - 5-3. $b := b - \alpha\mathrm{d}b$

- **Vectorizing *for* loop for multiple features**: 
    - Combine $w_1, w_2, ..., w_n$ into $\textbf{w}$ and $x_1, x_2, ..., x_n$ into $\textbf{x}$, and compute $\mathrm{d}\textbf{w}\ += \textbf{x}^{(i)}\mathrm{d}z^{(i)}$  
    
$\boxed{z^{i}\ =\ w^Tx^{(i)}+b, a^{(i)}\ =\ \sigma(z^{(i)})}$, *for* $i\ \mathrm{in\ range}(m)$
- **Vectorizing logistic regression prediction *a***
    - $\textbf{z} = [z^{(1)}\ z^{(2)}\ ...\ z^{(m)}],\textbf{X} = [x^{(1)}\ x^{(2)}\ ...\ x^{(m)}]\Rightarrow \textbf{z} = w^T\textbf{X}+\textbf{b},\ where:\ \textbf{b}=[b\ b\ ...\ b],1\times m$
    - $[z^{(1)}\ z^{(2)}\ ...\ z^{(m)}] = [w_1\ w_2\ ...\ w_n]\left[\begin{array}{c}
x_1^{(1)} & x_1^{(2)} & ... & x_1^{(m)}\\
x_2^{(1)} & x_2^{(2)} & ... & x_2^{(m)}\\
\vdots & \vdots & ... & \vdots\\
x_n^{(1)} & x_n^{(2)} & ... & x_n^{(m)}
\end{array}\right]\ +[b\ b\ ...\ b] = [\textbf{w}^T\textbf{x}^{(1)}+b\ \ \textbf{w}^T\textbf{x}^{(2)}+b\ \ ...\ \ \textbf{w}^T\textbf{x}^{(m)}+b]$
        - **Python code**: Z = np.dot(w.T, X) + b (python expands *b* to 1*m vector and add it to the vector; **broadcasting**)
    - $\textbf{a} = \sigma(\textbf{z})$

$\boxed{\mathrm{d}z^{(i)}\ =\ a^{(i)}\ -\ y^{(i)}}$
- **Vectorizing logistic regression's gradient computation for all *m* training samples**:
    - **Vectorizing dz**:
        - $\mathrm{d}\textbf{z} = [\mathrm{d}z^{(1)}\ \mathrm{d}z^{(2)}\ ...\ \mathrm{d}z^{(m)}],\textbf{y} = [y^{(1)}\ y^{(2)}\ ...\ y^{(m)}]\Rightarrow \mathrm{d}\textbf{z}\ =\ \textbf{a}\ -\ \textbf{y}$
    - **Vectorizing db**:
        - **Python code**: db = 1/m\*np.sum(dz)
        - $\mathrm{d}b\ = \frac{1}{m}\sum\limits_{i=1}^{m} \mathrm{d}\textbf{z}$
    - **Vectorizing dw**:
        - **Python code**: dw = 1/m\*X\*dZ.T
        - $\mathrm{d}\textbf{w}\ = \frac{1}{m}\textbf{X}\mathrm{d}z^T \Leftrightarrow [w_1\ w_2\ ...\ w_n] =\frac{1}{m}\left[\begin{array}{c}
x_1^{(1)} & x_1^{(2)} & ... & x_1^{(m)}\\
x_2^{(1)} & x_2^{(2)} & ... & x_2^{(m)}\\
\vdots & \vdots & ... & \vdots\\
x_n^{(1)} & x_n^{(2)} & ... & x_n^{(m)}
\end{array}\right] \left[\begin{array}{c}
\mathrm{d}z^{(1)}\\
\mathrm{d}z^{(2)}\\
\vdots\\
\mathrm{d}z^{(m)}
\end{array}\right] = \left[\begin{array}{c}
\frac{1}{m}(x_1^{(1)}\mathrm{d}z^{(1)} + x_1^{(2)}\mathrm{d}z^{(2)} + ... + x_1^{(m)}\mathrm{d}z^{(m)})\\
\frac{1}{m}(x_2^{(1)}\mathrm{d}z^{(1)} + x_2^{(2)}\mathrm{d}z^{(2)} + ... + x_2^{(m)}\mathrm{d}z^{(m)})\\
\vdots\\
\frac{1}{m}(x_{n_x}^{(1)}\mathrm{d}z^{(1)} + x_{n_x}^{(2)}\mathrm{d}z^{(2)} + ... + x_{n_x}^{(m)}\mathrm{d}z^{(m)})
\end{array}\right]$

- **Overall flow for one step of gradient descent**:
    - Round 0:
        - $\textbf{z} = \textbf{w}^T\textbf{X}+b$
        - $\textbf{a} = \sigma(\textbf{z})$
        - $J = -\frac{1}{m}\sum\limits_{i=1}^{m}[y^{(i)}\log a^{(i)}+(1-y^{(i)})\log(1-a^{(i)})]$
    - Round 1+:
        - $\mathrm{d}\textbf{z} = \textbf{a} - \textbf{y}$
        - $\mathrm{d}\textbf{w} = \frac{1}{m}\textbf{X}\mathrm{d}\textbf{z}^T$
        - $\mathrm{d}b = \frac{1}{m}\sum\limits_{i=1}^{m} \mathrm{d}\textbf{z}$
        - $\textbf{w} := \textbf{w} - \alpha\mathrm{d}\textbf{w}$
        - $b := b - \alpha\mathrm{d}b$
        - $\textbf{z} = \textbf{w}^T\textbf{X}+b$
        - $\textbf{a} = \sigma(\textbf{z})$
        - $J = -\frac{1}{m}\sum\limits_{i=1}^{m}[y^{(i)}\log a^{(i)}+(1-y^{(i)})\log(1-a^{(i)})]$

#### 3. Broadcasting in Python

- **Meaning**: when computing a number with a $1\times x$ matrix, the number will be replicated to a $1\times x$ matrix and be computed with the matrix. When a matrix with shape of $m\times n$ computes with a row vector $1\times n$ or a column vector $m\times 1$, the row/column of the vector will be replicated to the column/row side until reaching a shape of $m\times n$.


In [18]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])

cal = A.sum(axis=0) # 0 means vertical computation and 1 means horizontal computation
print(cal)

[ 59.  239.  155.4  76.9]


In [15]:
percentage = 100*A/(cal.reshape(1,4))
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [20]:
A = np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
B = np.array([10,20,30,40])
C = np.array([[10],
            [20],
            [30]])

D = A+B
E = A+C

print('D=A+B (vertical broadcasting):\n',D)
print('E=A+C (horizontal broadcasting):\n',E)

D=A+B (vertical broadcasting):
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]
E=A+C (horizontal broadcasting):
 [[11 12 13 14]
 [25 26 27 28]
 [39 40 41 42]]


#### 4. Array Type in Python

- **Rank 1 array**
    - Contains only one dimension in its shape, shown as *(n,)*
    - Is created with one pair of bracket or without an indication of two dimensions
    - May cause non-intuitive troubles; **should be generally avoided**

In [23]:
a1 = np.array([1,2,3,4,5])
a2 = np.random.randn(5)

print('the shape of a1 is: ', a1.shape)
print('the shape of a2 is: ', a2.shape)

the shape of a1 is:  (5,)
the shape of a2 is:  (5,)


- **Row vector**
    - Created by setting the number of rows as 1, or by using two brackets in *np.array*
    - Can be transposed to a column vector

In [25]:
r1 = np.array([[1,2,3,4,5]])
r2 = np.random.randn(1,5)

print('the shape of r1 is: ', r1.shape)
print('the shape of r2 is: ', r2.shape)

c1_r1 = r1.T

print('the shape of r1 after transposition is: ', c1_r1.shape)

the shape of r1 is:  (1, 5)
the shape of r2 is:  (1, 5)
the shape of r1 after transposition is:  (5, 1)


- **Column vector**
    - Created by setting the number of columns as 1, or by using a big bracket enclosing multiple small brackets each with one value in *np.array*
    - Can be transposed to a row vector

In [26]:
c1 = np.array([[1],
            [2],
            [3],
            [4],
            [5]])
c2 = np.random.randn(5,1)

print('the shape of c1 is: ', c1.shape)
print('the shape of c2 is: ', c2.shape)

r1_c1 = c1.T

print('the shape of c1 after transposition is: ', r1_c1.shape)

the shape of c1 is:  (5, 1)
the shape of c2 is:  (5, 1)
the shape of c1 after transposition is:  (1, 5)
